---
- name: Import public key used by the package management system
  apt_key:
    url: https://www.mongodb.org/static/pgp/server-6.0.asc
    state: present

- name: Create a list file for MongoDB
  apt_repository:
    repo: "deb [ arch=amd64,arm64 ] https://repo.mongodb.org/apt/ubuntu jammy/mongodb-org/6.0 multiverse"
    state: present
    filename: mongodb-org-6.0

- name: Reload local package database
  apt:
    update_cache: yes

- name: Install the MongoDB packages
  apt:
    name: mongodb-org
    state: present

- name: Start MongoDB
  service:
    name: mongod
    state: started
    enabled: yes

- name: Ensure MongoDB is listening on all interfaces (optional, for remote access)
  lineinfile:
    path: /etc/mongod.conf
    regexp: "^  bindIp: 127.0.0.1"
    line: "  bindIp: 0.0.0.0"
  notify: restart mongodb
